version: '3.8'

services:
  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    container_name: service-registry
    environment:
      - SPRING_PROFILES_ACTIVE=docker